---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs-pvc
  namespace: cs-ns
  labels:
    app: codeserver
    name: cs-pvc
spec:
  storageClassName: do-block-storage 
  accessModes: [ ReadWriteOnce ]
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs-deploy
  namespace: cs-ns
  labels:
    app: codeserver
    name: cs-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
      name: cs-po
  template:
    metadata:
      name: cs-po
      labels:
        app: codeserver
        name: cs-po
    spec:
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: cs-pvc
      containers:
      - name: cs-container
        image: linuxserver/code-server:4.18.0
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: cs-cm
        - secretRef:
            name: cs-secret
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: data-vol
          mountPath: /config/workspace

---
apiVersion: v1
kind: Service
metadata:
  name: cs-svc
  namespace: cs-ns
  labels:
    app: codeserver
    name: cs-svc
spec:
  type: ClusterIP
  selector:
    app: codeserver
    name: cs-po
  ports:
  - port: 8443
    targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs-ing
  namespace: cs-ns
  labels:
    app: codeserver
    name: cs-ing
spec:
  ingressClassName: nginx
  rules:
  - host: code-server.167.172.7.205.nip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cs-svc
            port:
              number: 8443
