---
apiVersion: v1
kind: Namespace
metadata:
  name: cs-ns
  labels:
    app: codeserver

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs-cm
  namespace: cs-ns
  labels:
    app: codeserver
    name: cs-cm
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-server.167.172.7.205.nip.io

